apiVersion: v1
kind: Service
metadata:
  name: advanced-nodejs-app-v30
spec:
  selector:
    app: advanced-nodejs-app-v30
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
